import { Inter } from "next/font/google";
import "./globals.css";
import NavbarComponent from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kalam KAS Experts",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black">
        <NavbarComponent/>
        {children}
        </body>
    </html>
  )
}
